languageCode: en-us, es-es
theme: PaperMod

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableEmoji: true

params:
  profileMode:
    enabled: false
    title: Lucas Miranda
  homeInfoParams:
    Title: Lucas Miranda
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  math: false
  ShowOnlySelectedPubs: false
  ShowReadingTime: true
  description: "An ape in awe. Postdoctoral researcher at EPFL MLBio."
  keywords: ["Machine Learning", "Medical Informatics", "Bioinformatics"]
  author: Me
  assets:
    favicon: "/assets/favicon.ico"

  SocialIcons:
    - name: github
      url: "https://github.com/lucasmiranda42"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/lucasmiranda42/"
    - name: bluesky
      url: "https://bsky.app/profile/lucasmiranda42.bsky.social"
    - name: GoogleScholar
      url: "https://scholar.google.com/citations?user=IVorpyEAAAAJ&hl=en"
    - name: email
      url: "mailto:lucas.miranda@epfl.ch"
    - name: deezer
      url: "https://www.deezer.com/de/profile/6343103503"

languages:
  en:
    title : "Lucas Miranda"
    disabled: false
    languageName: "English"
    contentDir: content/en
    languageCode: en-us
    weight: 1
    params:
      languageAltTitle: 🇬🇧
      homeInfoParams:
        Title: Lucas Miranda
        Content: >
          I am a postdoctoral researcher at [EPFL MLBio](https://brbiclab.epfl.ch/), directed by Maria Brbić.
          Previously, I was a postdoctoral researcher at the [Max Planck Institute of Biochemistry](https://www.biochem.mpg.de/en) (MLSB, Karsten Borgwardt).
          I obtained my PhD in 2024 from the Technical University of Munich (TUM), under the supervision of Bertram Müller-Myhsok.
          My research focuses on the development of machine learning methods for biochemical and medical informatics problems, with a special focus on spatial omics.
        imageUrl: "profile.png"
        imageTitle: ProfileMode image
        imageWidth: 180
        imageHeight: 180
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Bio
          url: about/
          weight: 10
        - name: Publications
          url: pubs/
          weight: 15
        - name: Software
          url: software/
          weight: 20
        - name: Blog
          url: blog/
          weight: 25
        - name: Search
          url: search/
          weight: 30

  es:
    title : "Lucas Miranda"
    disabled: false
    languageName: "Español"
    contentDir: content/es
    languageCode: es-es
    weight: 2
    params:
      languageAltTitle: 🧉
      homeInfoParams:
        Title: Lucas Miranda
        Content: >
          Soy investigador postdoctoral en [EPFL MLBio](https://brbiclab.epfl.ch/), dirigido por Maria Brbić.
          Antes también fui postdoc en el [Instituto Max Planck de Bioquímica](https://www.biochem.mpg.de/en) (MLSB, Karsten Borgwardt).
          Obtuve mi doctorado en 2024 de la Universidad Técnica de Munich (TUM), bajo la supervisión de Bertram Müller-Myhsok.
          Mi investigación se centra en el desarrollo de métodos de aprendizaje automático para problemas de bioinformática y medicina, con un enfoque particular en ómicas espaciales.
        imageUrl: "profile.png"
        imageTitle: ProfileMode image
        imageWidth: 180
        imageHeight: 180

    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Bio
          url: about/
          weight: 10
        - name: Publicaciones
          url: pubs/
          weight: 15
        - name: Software
          url: software/
          weight: 20
        - name: Blog
          url: blog/
          weight: 25
        - name: Búsqueda
          url: search/
          weight: 30

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

outputs: 
  home:   
    - HTML   
    - RSS   
    - JSON